#!/bin/bash

######################################################################
#
#	Catch signals...
#
######################################################################

trap 'rm -f "${tmpfile}" > /dev/null 2>&1' 0
trap "exit 2" 1 2 3 15

######################################################################
#
#	Setup variables...
#
######################################################################

tmpfile="/tmp/`basename $0`-$$.tmp"



[ -h "$0" ] && scriptDir=$(dirname `readlink $0`) || scriptDir=$( cd `dirname $0` && pwd)

functions=${scriptDir}/../functions.sh
settings=${scriptDir}/../settings.cfg

# Sanity checks

[ -r ${functions} ] && source ${functions} || { logger -t $(basename $0) "FATAL: Missing '${functions}', Aborting" ; exit 1; }
[ -r ${settings} ]  && source ${settings}  || { logger -t $(basename $0) "FATAL: Missing '${settings}', Aborting" ; exit 1; }

sun_set="$(awk 'END{print $1,$3}' /var/rfxcmd/sun-rise-set.log)"
sun_set_epoch=$(date +%s --date="${sun_set}")

minutes_before=${BEFORE_SUNSET}
minutes_before=${minutes_before:=45}

lights_on=$(date "+%M %H" --date=@$((${sun_set_epoch}-(${minutes_before}*60))))

#
#	Generate cron job
#

cat <<- CAT_EOF
#
#	Cron job generated by script $(basename ${0})
#
#       Lights on at ${minutes_before} minutes before sunset
#
${lights_on} * * * pi /home/pi/rfx-commands/commands/cmd-to-nexa.sh "group on"
CAT_EOF
exit 0
