#!/bin/bash
# pubnummgr daemon
# chkconfig: 345 20 80
# description: pubnummgr daemon
# processname: pubnummgr.py

### BEGIN INIT INFO
# Provides:          pubnubmgr
# Required-Start:    $syslog $remote_fs $network $time
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the rfxcmd server daemon
# Description:       Read data from rfxcom
### END INIT INFO

##############################################################################
#
# Note, you might need to change the parameters below, the current settings
# are for default setup.
#
##############################################################################

source /home/pi/rfx-commands/settings.cfg

NAME=pubnubmgr
DESC="pubnubmgr daemon startup script"
PIDFILE=/var/run/$NAME.pid

SCRIPTNAME=/etc/init.d/$NAME
HISTORYSCRIPT="/home/pi/rfx-commands/history/history.sh"
DAEMON=/home/pi/rfx-commands/pubnub/pubnubmgr.py
DAEMONOPTS="--pid-file ${PIDFILE} --allow-publish-file ${PUBNUB_ALLOWPUBLISH} --pubnub-subkey ${PUBNUB_SUBKEY} --pubnub-pubkey ${PUBNUB_PUBKEY} --pubnub-channel ${PUBNUB_CHANNEL} --external-history ${HISTORYSCRIPT}"

case "$1" in
	start)
		${DAEMON} --start  ${DAEMONOPTS}
	;;
	status)
		${DAEMON} --status ${DAEMONOPTS}
	;;

	stop)
		${DAEMON} --stop   ${DAEMONOPTS}
	;;

	restart)
  		${DAEMON} --restart ${DAEMONOPTS}
	;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
